/*
 * psc-api-maj-v2
 * API CRUD for Personnels et Structures de santé
 *
 * OpenAPI spec version: 2.0
 * Contact: superviseurs.psc@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * Mapping identifier to Ps
 */
@Schema(description = "Mapping identifier to Ps")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-23T09:52:58.504Z[GMT]")
public class PsRef {
  @JsonProperty("nationalIdRef")
  private String nationalIdRef = null;

  @JsonProperty("nationalId")
  private String nationalId = null;

  @JsonProperty("activated")
  private BigDecimal activated = null;

  @JsonProperty("deactivated")
  private BigDecimal deactivated = null;

  public PsRef nationalIdRef(String nationalIdRef) {
    this.nationalIdRef = nationalIdRef;
    return this;
  }

   /**
   * Get nationalIdRef
   * @return nationalIdRef
  **/
  @Schema(required = true, description = "")
  public String getNationalIdRef() {
    return nationalIdRef;
  }

  public void setNationalIdRef(String nationalIdRef) {
    this.nationalIdRef = nationalIdRef;
  }

  public PsRef nationalId(String nationalId) {
    this.nationalId = nationalId;
    return this;
  }

   /**
   * Get nationalId
   * @return nationalId
  **/
  @Schema(required = true, description = "")
  public String getNationalId() {
    return nationalId;
  }

  public void setNationalId(String nationalId) {
    this.nationalId = nationalId;
  }

  public PsRef activated(BigDecimal activated) {
    this.activated = activated;
    return this;
  }

   /**
   * Get activated
   * @return activated
  **/
  @Schema(description = "")
  public BigDecimal getActivated() {
    return activated;
  }

  public void setActivated(BigDecimal activated) {
    this.activated = activated;
  }

  public PsRef deactivated(BigDecimal deactivated) {
    this.deactivated = deactivated;
    return this;
  }

   /**
   * Get deactivated
   * @return deactivated
  **/
  @Schema(description = "")
  public BigDecimal getDeactivated() {
    return deactivated;
  }

  public void setDeactivated(BigDecimal deactivated) {
    this.deactivated = deactivated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PsRef psRef = (PsRef) o;
    return Objects.equals(this.nationalIdRef, psRef.nationalIdRef) &&
        Objects.equals(this.nationalId, psRef.nationalId) &&
        Objects.equals(this.activated, psRef.activated) &&
        Objects.equals(this.deactivated, psRef.deactivated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nationalIdRef, nationalId, activated, deactivated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PsRef {\n");
    
    sb.append("    nationalIdRef: ").append(toIndentedString(nationalIdRef)).append("\n");
    sb.append("    nationalId: ").append(toIndentedString(nationalId)).append("\n");
    sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
    sb.append("    deactivated: ").append(toIndentedString(deactivated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
