/*
 * psc-api-maj-v2
 * API CRUD for Personnels et Structures de santé
 *
 * OpenAPI spec version: 3.0
 * Contact: superviseurs.psc@esante.gouv.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package fr.ans.psc.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Situation d exercice
 */
@Schema(description = "Situation d exercice")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-22T12:08:03.211Z[GMT]")
public class WorkSituation {
  @SerializedName("situId")
  private String situId = null;

  @SerializedName("modeCode")
  private String modeCode = null;

  @SerializedName("activitySectorCode")
  private String activitySectorCode = null;

  @SerializedName("pharmacistTableSectionCode")
  private String pharmacistTableSectionCode = null;

  @SerializedName("roleCode")
  private String roleCode = null;

  @SerializedName("siteSIRET")
  private String siteSIRET = null;

  @SerializedName("siteSIREN")
  private String siteSIREN = null;

  @SerializedName("siteFINESS")
  private String siteFINESS = null;

  @SerializedName("legalEstablishmentFINESS")
  private String legalEstablishmentFINESS = null;

  @SerializedName("structureTechnicalId")
  private String structureTechnicalId = null;

  @SerializedName("legalCommercialName")
  private String legalCommercialName = null;

  @SerializedName("publicCommercialName")
  private String publicCommercialName = null;

  @SerializedName("recipientAdditionalInfo")
  private String recipientAdditionalInfo = null;

  @SerializedName("geoLocationAdditionalInfo")
  private String geoLocationAdditionalInfo = null;

  @SerializedName("streetNumber")
  private String streetNumber = null;

  @SerializedName("streetNumberRepetitionIndex")
  private String streetNumberRepetitionIndex = null;

  @SerializedName("streetCategoryCode")
  private String streetCategoryCode = null;

  @SerializedName("streetLabel")
  private String streetLabel = null;

  @SerializedName("distributionMention")
  private String distributionMention = null;

  @SerializedName("cedexOffice")
  private String cedexOffice = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("communeCode")
  private String communeCode = null;

  @SerializedName("countryCode")
  private String countryCode = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("phone2")
  private String phone2 = null;

  @SerializedName("fax")
  private String fax = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("departmentCode")
  private String departmentCode = null;

  @SerializedName("oldStructureId")
  private String oldStructureId = null;

  @SerializedName("registrationAuthority")
  private String registrationAuthority = null;

  public WorkSituation situId(String situId) {
    this.situId = situId;
    return this;
  }

   /**
   * Get situId
   * @return situId
  **/
  @Schema(description = "")
  public String getSituId() {
    return situId;
  }

  public void setSituId(String situId) {
    this.situId = situId;
  }

  public WorkSituation modeCode(String modeCode) {
    this.modeCode = modeCode;
    return this;
  }

   /**
   * Get modeCode
   * @return modeCode
  **/
  @Schema(description = "")
  public String getModeCode() {
    return modeCode;
  }

  public void setModeCode(String modeCode) {
    this.modeCode = modeCode;
  }

  public WorkSituation activitySectorCode(String activitySectorCode) {
    this.activitySectorCode = activitySectorCode;
    return this;
  }

   /**
   * Get activitySectorCode
   * @return activitySectorCode
  **/
  @Schema(description = "")
  public String getActivitySectorCode() {
    return activitySectorCode;
  }

  public void setActivitySectorCode(String activitySectorCode) {
    this.activitySectorCode = activitySectorCode;
  }

  public WorkSituation pharmacistTableSectionCode(String pharmacistTableSectionCode) {
    this.pharmacistTableSectionCode = pharmacistTableSectionCode;
    return this;
  }

   /**
   * Get pharmacistTableSectionCode
   * @return pharmacistTableSectionCode
  **/
  @Schema(description = "")
  public String getPharmacistTableSectionCode() {
    return pharmacistTableSectionCode;
  }

  public void setPharmacistTableSectionCode(String pharmacistTableSectionCode) {
    this.pharmacistTableSectionCode = pharmacistTableSectionCode;
  }

  public WorkSituation roleCode(String roleCode) {
    this.roleCode = roleCode;
    return this;
  }

   /**
   * Get roleCode
   * @return roleCode
  **/
  @Schema(description = "")
  public String getRoleCode() {
    return roleCode;
  }

  public void setRoleCode(String roleCode) {
    this.roleCode = roleCode;
  }

  public WorkSituation siteSIRET(String siteSIRET) {
    this.siteSIRET = siteSIRET;
    return this;
  }

   /**
   * Get siteSIRET
   * @return siteSIRET
  **/
  @Schema(description = "")
  public String getSiteSIRET() {
    return siteSIRET;
  }

  public void setSiteSIRET(String siteSIRET) {
    this.siteSIRET = siteSIRET;
  }

  public WorkSituation siteSIREN(String siteSIREN) {
    this.siteSIREN = siteSIREN;
    return this;
  }

   /**
   * Get siteSIREN
   * @return siteSIREN
  **/
  @Schema(description = "")
  public String getSiteSIREN() {
    return siteSIREN;
  }

  public void setSiteSIREN(String siteSIREN) {
    this.siteSIREN = siteSIREN;
  }

  public WorkSituation siteFINESS(String siteFINESS) {
    this.siteFINESS = siteFINESS;
    return this;
  }

   /**
   * Get siteFINESS
   * @return siteFINESS
  **/
  @Schema(description = "")
  public String getSiteFINESS() {
    return siteFINESS;
  }

  public void setSiteFINESS(String siteFINESS) {
    this.siteFINESS = siteFINESS;
  }

  public WorkSituation legalEstablishmentFINESS(String legalEstablishmentFINESS) {
    this.legalEstablishmentFINESS = legalEstablishmentFINESS;
    return this;
  }

   /**
   * Get legalEstablishmentFINESS
   * @return legalEstablishmentFINESS
  **/
  @Schema(description = "")
  public String getLegalEstablishmentFINESS() {
    return legalEstablishmentFINESS;
  }

  public void setLegalEstablishmentFINESS(String legalEstablishmentFINESS) {
    this.legalEstablishmentFINESS = legalEstablishmentFINESS;
  }

  public WorkSituation structureTechnicalId(String structureTechnicalId) {
    this.structureTechnicalId = structureTechnicalId;
    return this;
  }

   /**
   * Get structureTechnicalId
   * @return structureTechnicalId
  **/
  @Schema(description = "")
  public String getStructureTechnicalId() {
    return structureTechnicalId;
  }

  public void setStructureTechnicalId(String structureTechnicalId) {
    this.structureTechnicalId = structureTechnicalId;
  }

  public WorkSituation legalCommercialName(String legalCommercialName) {
    this.legalCommercialName = legalCommercialName;
    return this;
  }

   /**
   * Get legalCommercialName
   * @return legalCommercialName
  **/
  @Schema(description = "")
  public String getLegalCommercialName() {
    return legalCommercialName;
  }

  public void setLegalCommercialName(String legalCommercialName) {
    this.legalCommercialName = legalCommercialName;
  }

  public WorkSituation publicCommercialName(String publicCommercialName) {
    this.publicCommercialName = publicCommercialName;
    return this;
  }

   /**
   * Get publicCommercialName
   * @return publicCommercialName
  **/
  @Schema(description = "")
  public String getPublicCommercialName() {
    return publicCommercialName;
  }

  public void setPublicCommercialName(String publicCommercialName) {
    this.publicCommercialName = publicCommercialName;
  }

  public WorkSituation recipientAdditionalInfo(String recipientAdditionalInfo) {
    this.recipientAdditionalInfo = recipientAdditionalInfo;
    return this;
  }

   /**
   * Get recipientAdditionalInfo
   * @return recipientAdditionalInfo
  **/
  @Schema(description = "")
  public String getRecipientAdditionalInfo() {
    return recipientAdditionalInfo;
  }

  public void setRecipientAdditionalInfo(String recipientAdditionalInfo) {
    this.recipientAdditionalInfo = recipientAdditionalInfo;
  }

  public WorkSituation geoLocationAdditionalInfo(String geoLocationAdditionalInfo) {
    this.geoLocationAdditionalInfo = geoLocationAdditionalInfo;
    return this;
  }

   /**
   * Get geoLocationAdditionalInfo
   * @return geoLocationAdditionalInfo
  **/
  @Schema(description = "")
  public String getGeoLocationAdditionalInfo() {
    return geoLocationAdditionalInfo;
  }

  public void setGeoLocationAdditionalInfo(String geoLocationAdditionalInfo) {
    this.geoLocationAdditionalInfo = geoLocationAdditionalInfo;
  }

  public WorkSituation streetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
    return this;
  }

   /**
   * Get streetNumber
   * @return streetNumber
  **/
  @Schema(description = "")
  public String getStreetNumber() {
    return streetNumber;
  }

  public void setStreetNumber(String streetNumber) {
    this.streetNumber = streetNumber;
  }

  public WorkSituation streetNumberRepetitionIndex(String streetNumberRepetitionIndex) {
    this.streetNumberRepetitionIndex = streetNumberRepetitionIndex;
    return this;
  }

   /**
   * Get streetNumberRepetitionIndex
   * @return streetNumberRepetitionIndex
  **/
  @Schema(description = "")
  public String getStreetNumberRepetitionIndex() {
    return streetNumberRepetitionIndex;
  }

  public void setStreetNumberRepetitionIndex(String streetNumberRepetitionIndex) {
    this.streetNumberRepetitionIndex = streetNumberRepetitionIndex;
  }

  public WorkSituation streetCategoryCode(String streetCategoryCode) {
    this.streetCategoryCode = streetCategoryCode;
    return this;
  }

   /**
   * Get streetCategoryCode
   * @return streetCategoryCode
  **/
  @Schema(description = "")
  public String getStreetCategoryCode() {
    return streetCategoryCode;
  }

  public void setStreetCategoryCode(String streetCategoryCode) {
    this.streetCategoryCode = streetCategoryCode;
  }

  public WorkSituation streetLabel(String streetLabel) {
    this.streetLabel = streetLabel;
    return this;
  }

   /**
   * Get streetLabel
   * @return streetLabel
  **/
  @Schema(description = "")
  public String getStreetLabel() {
    return streetLabel;
  }

  public void setStreetLabel(String streetLabel) {
    this.streetLabel = streetLabel;
  }

  public WorkSituation distributionMention(String distributionMention) {
    this.distributionMention = distributionMention;
    return this;
  }

   /**
   * Get distributionMention
   * @return distributionMention
  **/
  @Schema(description = "")
  public String getDistributionMention() {
    return distributionMention;
  }

  public void setDistributionMention(String distributionMention) {
    this.distributionMention = distributionMention;
  }

  public WorkSituation cedexOffice(String cedexOffice) {
    this.cedexOffice = cedexOffice;
    return this;
  }

   /**
   * Get cedexOffice
   * @return cedexOffice
  **/
  @Schema(description = "")
  public String getCedexOffice() {
    return cedexOffice;
  }

  public void setCedexOffice(String cedexOffice) {
    this.cedexOffice = cedexOffice;
  }

  public WorkSituation postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @Schema(description = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public WorkSituation communeCode(String communeCode) {
    this.communeCode = communeCode;
    return this;
  }

   /**
   * Get communeCode
   * @return communeCode
  **/
  @Schema(description = "")
  public String getCommuneCode() {
    return communeCode;
  }

  public void setCommuneCode(String communeCode) {
    this.communeCode = communeCode;
  }

  public WorkSituation countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @Schema(description = "")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public WorkSituation phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public WorkSituation phone2(String phone2) {
    this.phone2 = phone2;
    return this;
  }

   /**
   * Get phone2
   * @return phone2
  **/
  @Schema(description = "")
  public String getPhone2() {
    return phone2;
  }

  public void setPhone2(String phone2) {
    this.phone2 = phone2;
  }

  public WorkSituation fax(String fax) {
    this.fax = fax;
    return this;
  }

   /**
   * Get fax
   * @return fax
  **/
  @Schema(description = "")
  public String getFax() {
    return fax;
  }

  public void setFax(String fax) {
    this.fax = fax;
  }

  public WorkSituation email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public WorkSituation departmentCode(String departmentCode) {
    this.departmentCode = departmentCode;
    return this;
  }

   /**
   * Get departmentCode
   * @return departmentCode
  **/
  @Schema(description = "")
  public String getDepartmentCode() {
    return departmentCode;
  }

  public void setDepartmentCode(String departmentCode) {
    this.departmentCode = departmentCode;
  }

  public WorkSituation oldStructureId(String oldStructureId) {
    this.oldStructureId = oldStructureId;
    return this;
  }

   /**
   * Get oldStructureId
   * @return oldStructureId
  **/
  @Schema(description = "")
  public String getOldStructureId() {
    return oldStructureId;
  }

  public void setOldStructureId(String oldStructureId) {
    this.oldStructureId = oldStructureId;
  }

  public WorkSituation registrationAuthority(String registrationAuthority) {
    this.registrationAuthority = registrationAuthority;
    return this;
  }

   /**
   * Get registrationAuthority
   * @return registrationAuthority
  **/
  @Schema(description = "")
  public String getRegistrationAuthority() {
    return registrationAuthority;
  }

  public void setRegistrationAuthority(String registrationAuthority) {
    this.registrationAuthority = registrationAuthority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkSituation workSituation = (WorkSituation) o;
    return Objects.equals(this.situId, workSituation.situId) &&
        Objects.equals(this.modeCode, workSituation.modeCode) &&
        Objects.equals(this.activitySectorCode, workSituation.activitySectorCode) &&
        Objects.equals(this.pharmacistTableSectionCode, workSituation.pharmacistTableSectionCode) &&
        Objects.equals(this.roleCode, workSituation.roleCode) &&
        Objects.equals(this.siteSIRET, workSituation.siteSIRET) &&
        Objects.equals(this.siteSIREN, workSituation.siteSIREN) &&
        Objects.equals(this.siteFINESS, workSituation.siteFINESS) &&
        Objects.equals(this.legalEstablishmentFINESS, workSituation.legalEstablishmentFINESS) &&
        Objects.equals(this.structureTechnicalId, workSituation.structureTechnicalId) &&
        Objects.equals(this.legalCommercialName, workSituation.legalCommercialName) &&
        Objects.equals(this.publicCommercialName, workSituation.publicCommercialName) &&
        Objects.equals(this.recipientAdditionalInfo, workSituation.recipientAdditionalInfo) &&
        Objects.equals(this.geoLocationAdditionalInfo, workSituation.geoLocationAdditionalInfo) &&
        Objects.equals(this.streetNumber, workSituation.streetNumber) &&
        Objects.equals(this.streetNumberRepetitionIndex, workSituation.streetNumberRepetitionIndex) &&
        Objects.equals(this.streetCategoryCode, workSituation.streetCategoryCode) &&
        Objects.equals(this.streetLabel, workSituation.streetLabel) &&
        Objects.equals(this.distributionMention, workSituation.distributionMention) &&
        Objects.equals(this.cedexOffice, workSituation.cedexOffice) &&
        Objects.equals(this.postalCode, workSituation.postalCode) &&
        Objects.equals(this.communeCode, workSituation.communeCode) &&
        Objects.equals(this.countryCode, workSituation.countryCode) &&
        Objects.equals(this.phone, workSituation.phone) &&
        Objects.equals(this.phone2, workSituation.phone2) &&
        Objects.equals(this.fax, workSituation.fax) &&
        Objects.equals(this.email, workSituation.email) &&
        Objects.equals(this.departmentCode, workSituation.departmentCode) &&
        Objects.equals(this.oldStructureId, workSituation.oldStructureId) &&
        Objects.equals(this.registrationAuthority, workSituation.registrationAuthority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(situId, modeCode, activitySectorCode, pharmacistTableSectionCode, roleCode, siteSIRET, siteSIREN, siteFINESS, legalEstablishmentFINESS, structureTechnicalId, legalCommercialName, publicCommercialName, recipientAdditionalInfo, geoLocationAdditionalInfo, streetNumber, streetNumberRepetitionIndex, streetCategoryCode, streetLabel, distributionMention, cedexOffice, postalCode, communeCode, countryCode, phone, phone2, fax, email, departmentCode, oldStructureId, registrationAuthority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkSituation {\n");
    
    sb.append("    situId: ").append(toIndentedString(situId)).append("\n");
    sb.append("    modeCode: ").append(toIndentedString(modeCode)).append("\n");
    sb.append("    activitySectorCode: ").append(toIndentedString(activitySectorCode)).append("\n");
    sb.append("    pharmacistTableSectionCode: ").append(toIndentedString(pharmacistTableSectionCode)).append("\n");
    sb.append("    roleCode: ").append(toIndentedString(roleCode)).append("\n");
    sb.append("    siteSIRET: ").append(toIndentedString(siteSIRET)).append("\n");
    sb.append("    siteSIREN: ").append(toIndentedString(siteSIREN)).append("\n");
    sb.append("    siteFINESS: ").append(toIndentedString(siteFINESS)).append("\n");
    sb.append("    legalEstablishmentFINESS: ").append(toIndentedString(legalEstablishmentFINESS)).append("\n");
    sb.append("    structureTechnicalId: ").append(toIndentedString(structureTechnicalId)).append("\n");
    sb.append("    legalCommercialName: ").append(toIndentedString(legalCommercialName)).append("\n");
    sb.append("    publicCommercialName: ").append(toIndentedString(publicCommercialName)).append("\n");
    sb.append("    recipientAdditionalInfo: ").append(toIndentedString(recipientAdditionalInfo)).append("\n");
    sb.append("    geoLocationAdditionalInfo: ").append(toIndentedString(geoLocationAdditionalInfo)).append("\n");
    sb.append("    streetNumber: ").append(toIndentedString(streetNumber)).append("\n");
    sb.append("    streetNumberRepetitionIndex: ").append(toIndentedString(streetNumberRepetitionIndex)).append("\n");
    sb.append("    streetCategoryCode: ").append(toIndentedString(streetCategoryCode)).append("\n");
    sb.append("    streetLabel: ").append(toIndentedString(streetLabel)).append("\n");
    sb.append("    distributionMention: ").append(toIndentedString(distributionMention)).append("\n");
    sb.append("    cedexOffice: ").append(toIndentedString(cedexOffice)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    communeCode: ").append(toIndentedString(communeCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    phone2: ").append(toIndentedString(phone2)).append("\n");
    sb.append("    fax: ").append(toIndentedString(fax)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    departmentCode: ").append(toIndentedString(departmentCode)).append("\n");
    sb.append("    oldStructureId: ").append(toIndentedString(oldStructureId)).append("\n");
    sb.append("    registrationAuthority: ").append(toIndentedString(registrationAuthority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
